### ISSUE TITLE
Please publish 1.1.7 to Cocoapods

### ISSUE THREAD

**Issue by dmorrow** [segment-integrations/analytics-ios-integration-google-analytics#21]

**Comment by ladanazita** [comment]
Hi @dmorrow 

We actually can't release this version.

```
- NOTE  | [Segment-GoogleAnalytics/StaticLibWorkaround2] xcodebuild:  Segment-GoogleAnalytics/Pod/Classes/SEGGoogleAnalyticsIntegration.m:1:9: fatal error: 'GoogleAnalytics/GAIDictionaryBuilder.h' file not found
```

This solution eliminates manually adding the file step (outlined in [this solution](https://github.com/segment-integrations/analytics-ios-integration-google-analytics/pull/14)) but this subspec still relies on GA. Since the solution explicitly does not have GA as a dependency, Cocoapods will not accept this as a valid pod. In addition, since this solution exists in the podspec it would block all future releases. 

To leverage this solution, you will need to do 

```
target 'AnalyticsObjcTestApp' do
  pod 'Analytics'
  pod 'Segment-GoogleAnalytics/StaticLibWorkaround2', :git => 'https://github.com/segment-integrations/analytics-ios-integration-google-analytics.git', :tag => '1.1.7'
  pod 'GoogleAnalytics'
  pod 'GoogleIDFASupport'
end
```
